from heitang_kb_forge.skill.generator import generate_skill_package
from tests.v17_helpers import write_sample_package


def test_skill_generator_writes_skill_md(tmp_path):
    package = write_sample_package(tmp_path / "package")
    output = tmp_path / "skill"

    result = generate_skill_package(package, output, "Demo Knowledge Skill")

    assert result.skill_name == "Demo Knowledge Skill"
    assert (output / "SKILL.md").exists()
    assert "Generated by: rule_template" in (output / "SKILL.md").read_text(encoding="utf-8")
