from heitang_kb_forge.agent_package.prompts import make_agent_texts


def test_agent_prompt_generation_stays_evidence_bound():
    texts = make_agent_texts("Demo Agent", "generic", "rule_template")

    assert "Use only the connected knowledge package" in texts["system_prompt.md"]
    assert "Generated by: rule_template" in texts["soul.md"]
