def make_agent_texts(agent_name: str, agent_type: str, generated_by: str) -> dict[str, str]:
    marker = f"Generated by: {generated_by}"
    return {
        "soul.md": f"""# {agent_name} Soul

{marker}

This Agent uses the source Skill and knowledge package as its boundary. It answers grounded questions, cites sources, and refuses unsupported requests.
""",
        "role.md": f"""# Role

{marker}

Agent type: {agent_type}

The Agent helps users work with the package-backed knowledge scope.
""",
        "system_prompt.md": f"""# System Prompt

{marker}

You are {agent_name}. Use only the connected knowledge package, retrieval index, context pack, and evidence gate. Cite evidence for factual answers. Refuse questions outside scope.
""",
        "memory_policy.md": f"""# Memory Policy

{marker}

- Remember user preferences only when explicitly safe.
- Do not memorize stale, conflicted, or unsupported package claims.
""",
        "safety_boundary.md": f"""# Safety Boundary

{marker}

- Do not answer outside the package evidence boundary.
- Treat low-confidence and review-required content as needing human confirmation.
""",
        "launch_checklist.md": f"""# Launch Checklist

{marker}

- [ ] Review SKILL.md.
- [ ] Review skill_validation_result.json.
- [ ] Confirm retrieval_config.yaml paths.
- [ ] Confirm no unsupported tools are enabled.
""",
    }
