def render_agent_package_report(agent_name: str, output_files: list[str], generated_by: str) -> str:
    files = "\n".join(f"- {file_name}" for file_name in output_files)
    return f"""# Agent Package Report

- Agent: {agent_name}
- Generated by: {generated_by}

## Output Files

{files}
"""
