from heitang_kb_forge.schemas.llm_agent_schema import LLMAgentGenerationReport


def render_llm_agent_generation_report(report: LLMAgentGenerationReport) -> str:
    files = "\n".join(f"- {file_name}" for file_name in report.generated_files)
    review = "\n".join(f"- {item}" for item in report.review_required) or "- None"
    return f"""# LLM Agent Generation Report

- Enabled: {report.enabled}
- Provider: {report.provider}
- Fallback: {report.fallback}
- Generated by: {report.generated_by}

## Generated Files

{files}

## Review Required

{review}
"""
