from heitang_kb_forge.schemas.llm_skill_schema import LLMSkillGenerationReport


def render_llm_skill_generation_report(report: LLMSkillGenerationReport) -> str:
    files = "\n".join(f"- {file_name}" for file_name in report.generated_files)
    review = "\n".join(f"- {item}" for item in report.review_required) or "- None"
    return f"""# LLM Skill Generation Report

- Enabled: {report.enabled}
- Provider: {report.provider}
- Fallback: {report.fallback}
- Generated by: {report.generated_by}

## Generated Files

{files}

## Review Required

{review}
"""
