from pathlib import Path
import json


def make_examples(package: Path) -> tuple[str, list[dict]]:
    qa_pairs = _load_jsonl(package / "qa_pairs.jsonl")
    cases = []
    for index, item in enumerate(qa_pairs[:5], start=1):
        cases.append(
            {
                "case_id": f"skill_eval_{index}",
                "question": item.get("question", "What is covered by this package?"),
                "expected_behavior": "answer_with_citation",
                "source_path": item.get("source_path"),
                "chunk_id": item.get("chunk_id"),
            }
        )
    if not cases:
        cases.append(
            {
                "case_id": "skill_eval_1",
                "question": "What is covered by this package?",
                "expected_behavior": "answer_with_citation",
            }
        )
    md = ["# Examples", "", "Generated by: rule_template", ""]
    for case in cases:
        md.extend([f"## {case['case_id']}", "", f"- Question: {case['question']}", f"- Expected behavior: {case['expected_behavior']}", ""])
    return "\n".join(md), cases


def _load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
