from pathlib import Path
import json

from heitang_kb_forge.exporters.jsonl_exporter import write_jsonl
from heitang_kb_forge.skill.examples import make_examples
from heitang_kb_forge.skill.manifest import make_skill_manifest, render_skill_manifest_yaml
from heitang_kb_forge.skill.report import render_skill_generation_report
from heitang_kb_forge.skill.rules import make_rule_files
from heitang_kb_forge.skill.scope import make_knowledge_scope
from heitang_kb_forge.schemas.skill_schema import SkillGenerationResult


SKILL_PACKAGE_FILES = [
    "SKILL.md",
    "skill_manifest.yaml",
    "knowledge_scope.md",
    "answer_rules.md",
    "citation_rules.md",
    "boundary_rules.md",
    "refusal_rules.md",
    "style_rules.md",
    "evidence_policy.md",
    "examples.md",
    "eval_cases.jsonl",
    "skill_generation_report.md",
]


def generate_skill_package(
    package: Path,
    output: Path,
    skill_name: str,
    skill_type: str = "generic",
    generated_by: str = "rule_template",
) -> SkillGenerationResult:
    output.mkdir(parents=True, exist_ok=True)
    manifest = make_skill_manifest(package, skill_name, skill_type)
    rules = make_rule_files(generated_by)
    examples_md, eval_cases = make_examples(package)
    warnings = _warnings(package)

    (output / "SKILL.md").write_text(_render_skill_md(skill_name, skill_type, generated_by), encoding="utf-8")
    (output / "skill_manifest.yaml").write_text(render_skill_manifest_yaml(manifest), encoding="utf-8")
    (output / "knowledge_scope.md").write_text(make_knowledge_scope(package), encoding="utf-8")
    for file_name, text in rules.items():
        (output / file_name).write_text(text, encoding="utf-8")
    (output / "examples.md").write_text(examples_md, encoding="utf-8")
    write_jsonl(output / "eval_cases.jsonl", eval_cases)
    result = SkillGenerationResult(
        skill_id=manifest.skill_id,
        skill_name=skill_name,
        output_files=SKILL_PACKAGE_FILES,
        generated_by=generated_by,
        warnings=warnings,
    )
    (output / "skill_generation_report.md").write_text(render_skill_generation_report(result), encoding="utf-8")
    return result


def _render_skill_md(skill_name: str, skill_type: str, generated_by: str) -> str:
    return f"""---
name: {skill_name}
description: Use this skill to answer within the generated knowledge package scope.
---

# {skill_name}

Generated by: {generated_by}

## Goal

Provide package-grounded answers for `{skill_type}` tasks.

## Inputs and Outputs

- Input: user question and retrieved package evidence.
- Output: concise answer with citations or a refusal when evidence is missing.

## Knowledge Scope

Use `knowledge_scope.md` as the boundary.

## Answer Rules

Follow `answer_rules.md`, `citation_rules.md`, `boundary_rules.md`, and `refusal_rules.md`.
"""


def _warnings(package: Path) -> list[str]:
    warnings = []
    for path in [package / "review_queue.jsonl", package / "conflict_report.json", package / "staleness_report.json"]:
        if path.exists() and path.suffix == ".jsonl" and path.read_text(encoding="utf-8").strip():
            warnings.append("review_queue_not_empty")
        if path.exists() and path.suffix == ".json":
            payload = json.loads(path.read_text(encoding="utf-8"))
            if payload.get("status") == "warning":
                warnings.append(path.name)
    return warnings
