from heitang_kb_forge.schemas.skill_schema import SkillGenerationResult


def render_skill_generation_report(result: SkillGenerationResult) -> str:
    files = "\n".join(f"- {file_name}" for file_name in result.output_files)
    warnings = "\n".join(f"- {warning}" for warning in result.warnings) or "- None"
    return f"""# Skill Generation Report

- Skill: {result.skill_name}
- Skill ID: {result.skill_id}
- Generated by: {result.generated_by}

## Output Files

{files}

## Warnings

{warnings}
"""
