def make_rule_files(generated_by: str = "rule_template") -> dict[str, str]:
    marker = f"Generated by: {generated_by}"
    return {
        "answer_rules.md": f"""# Answer Rules

{marker}

- Answer only from package evidence.
- Prefer concise, source-grounded responses.
- Mark low-confidence or review-required content instead of treating it as fact.
""",
        "citation_rules.md": f"""# Citation Rules

{marker}

- Include source_path and chunk_id when making factual claims.
- Use citation strings from the package when available.
- Do not invent citations.
""",
        "boundary_rules.md": f"""# Boundary Rules

{marker}

- Stay within the knowledge_scope.md boundary.
- Treat outside-scope requests as unsupported.
- If evidence is missing, refuse or ask for review.
- Conflicted or outdated content must not become a strong rule.
""",
        "refusal_rules.md": f"""# Refusal Rules

{marker}

- Refuse unsupported questions clearly.
- Explain that the package does not contain enough evidence.
- Do not answer from general world knowledge.
""",
        "style_rules.md": f"""# Style Rules

{marker}

- Be direct, factual, and auditable.
- Separate evidence-backed facts from recommendations.
""",
        "evidence_policy.md": f"""# Evidence Policy

{marker}

- Strong answers require package evidence.
- Review-required evidence needs human confirmation.
- LLM-assisted text is advisory and must remain inside package scope.
""",
    }
