from pathlib import Path
import json


def make_knowledge_scope(package: Path) -> str:
    chunks = _load_jsonl(package / "chunks.jsonl")
    sources = sorted({chunk.get("source_path", "") for chunk in chunks if chunk.get("source_path")})
    titles = [chunk.get("title") or chunk.get("text", "")[:80] for chunk in chunks[:8]]
    source_lines = "\n".join(f"- {source}" for source in sources) or "- No sources found"
    title_lines = "\n".join(f"- {title}" for title in titles) or "- No covered topics found"
    return f"""# Knowledge Scope

Generated by: rule_template

## Source Files

{source_lines}

## Covered Topics

{title_lines}

## Boundary

Only answer questions that can be grounded in the source package. For unsupported questions, refuse or ask for review.
"""


def _load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
