from __future__ import annotations

from collections import Counter
from copy import deepcopy


AUDIT_VERSION = "3.6.0-alpha.1"
GENERATED_AT = "2026-06-07T00:00:00Z"
CURRENT_CORE_COMMIT = "cdfbb0e"
CURRENT_UI_COMMIT = "24dfa2b"


def architecture_gap_audit_report() -> dict:
    gap_items = [_gap(category, **item) for category, items in _CATEGORIES for item in items]
    counts = Counter(item["risk_level"] for item in gap_items)
    categories = [
        {
            "name": category,
            "item_count": len(items),
            "p0_count": len([item for item in items if item["risk_level"] == "P0"]),
            "p1_count": len([item for item in items if item["risk_level"] == "P1"]),
            "p2_count": len([item for item in items if item["risk_level"] == "P2"]),
        }
        for category, items in _CATEGORIES
    ]
    return {
        "audit_version": AUDIT_VERSION,
        "generated_at": GENERATED_AT,
        "current_core_commit": CURRENT_CORE_COMMIT,
        "current_ui_commit": CURRENT_UI_COMMIT,
        "ui_repo_dependency": False,
        "categories": categories,
        "gap_items": gap_items,
        "p0_items": [item for item in gap_items if item["risk_level"] == "P0"],
        "p1_items": [item for item in gap_items if item["risk_level"] == "P1"],
        "p2_items": [item for item in gap_items if item["risk_level"] == "P2"],
        "next_version_recommendations": {
            "v3.7": "Query Rewrite & Retrieval Planning",
            "v3.8": "RAG Retrieval Quality & Evaluation",
            "v3.9": "Local Workspace Storage & Memory Lifecycle",
            "v3.10": "Local Agent Runtime & Mother/Child Operations",
            "v3.11": "Golden Demo & Real Acceptance Smoke",
            "v3.12": "Product Hardening & Local Release Readiness",
            "v4.3": "Local Governance & Lifecycle Management",
            "v4.0": "Local Knowledge Workbench RC",
        },
        "blockers_before_v3_7": [
            "Confirm v3.7 scope remains query understanding contracts and retrieval planning only.",
            "Define stable query rewrite inputs, outputs, traces, and refusal diagnostics before implementation.",
            "Define verification-oriented retrieval planning and distinguish answer retrieval from validation retrieval.",
            "Keep UI integration frozen until Core contracts for v3.7 are generated and tested.",
        ],
        "risk_summary": {"P0": counts["P0"], "P1": counts["P1"], "P2": counts["P2"]},
    }


def _gap(category: str, **kwargs: object) -> dict:
    defaults = {
        "status": "missing",
        "risk_level": "P1",
        "evidence_files": [],
        "evidence_tests": [],
        "reason": "No stable Core implementation or contract evidence was found.",
        "user_impact": "Users cannot rely on this capability in the Golden Demo or Workbench.",
        "recommended_fix": "Add contract, report, CLI/config visibility, and focused tests in the mapped future version.",
        "target_version": "v3.12",
        "affects_core_contract": True,
        "affects_ui": False,
        "affects_golden_demo": False,
    }
    defaults.update(kwargs)
    defaults["category"] = category
    defaults.update(_llm_optionality(category, str(defaults["capability"]), str(defaults["target_version"])))
    return defaults


def _llm_optionality(category: str, capability: str, target_version: str) -> dict:
    local_path = "Use deterministic local rules, schemas, fixtures, reports, and package artifacts before any LLM assist."
    llm_path = "Optional assistive LLM layer may suggest drafts or explanations when explicitly configured; it must not be required."
    offline_fallback = "Offline fallback uses local fixtures, deterministic heuristics, and report-only outputs."
    if category == "RAG Query Understanding":
        local_path = "Deterministic query parsing, routing, rewrite constraints, and retrieval-plan schemas."
        llm_path = "Optional LLM may propose rewrite candidates, but local validation and refusal rules own the final contract."
        offline_fallback = "Use rule-based query classification and bounded local query variants."
    elif category == "RAG Retrieval Quality":
        local_path = "Local retrievers, rankers, traces, golden query fixtures, and deterministic scoring."
        llm_path = "Optional LLM may assist qualitative diagnostics, but retrieval metrics and pass/fail gates stay local."
        offline_fallback = "Use local corpus fixtures, deterministic rank/coverage scoring, and no-network evaluation."
    elif category == "External Retrieval for Knowledge Accuracy Verification":
        local_path = "Claim extraction, source records, cross-check states, freshness metadata, and verification traces run from local fixtures/contracts first."
        llm_path = "Optional LLM may summarize source disagreement or draft explanations after deterministic claim/evidence checks."
        offline_fallback = "Use local verification fixtures and mark external checks as not_run when network/providers are unavailable."
    elif category == "Local Document Parsing & PDF Token Reduction":
        local_path = "Local PDF/OCR/parser backends produce Markdown/JSON, confidence reports, and token-reduction metrics."
        llm_path = "Optional LLM may help summarize parsed Markdown or flag suspicious parse gaps, never parse by uploading raw PDFs by default."
        offline_fallback = "Use builtin parsers, optional local OCR, parser confidence reports, and no-cloud-upload invariants."
    elif category == "Agent / Skill System":
        local_path = "Generate and validate packages from local manifests, templates, policies, and smoke fixtures."
        llm_path = "Optional LLM may draft skill/agent text when configured; local validation remains authoritative."
        offline_fallback = "Use deterministic templates and local validation without provider configuration."
    elif category == "Agent Memory / Runtime":
        local_path = "Use local memory lifecycle schemas, queues, traces, and deterministic compaction/status reports."
        llm_path = "Optional LLM may summarize memory candidates after explicit configuration and review."
        offline_fallback = "Keep private memory, candidate queues, and lifecycle reports local and deterministic."
    elif category == "Storage / Workspace":
        local_path = "Use local workspace, registry, size accounting, cleanup suggestions, and storage contracts."
        llm_path = "Optional LLM may explain cleanup suggestions, but storage accounting stays deterministic."
        offline_fallback = "Use local_workspace backend and no platform-hosted user data."
    elif category == "Workbench / UI Contracts":
        local_path = "Generate static Core contracts, status files, and drift fixtures without UI runtime dependencies."
        llm_path = "Optional LLM may draft human-readable contract summaries, never required for contract generation."
        offline_fallback = "Use checked-in contract fixtures and deterministic JSON/Markdown outputs."
    elif category == "Product Readiness":
        local_path = "Use doctor checks, release blockers, local smoke fixtures, and deterministic readiness reports."
        llm_path = "Optional LLM may assist troubleshooting text, but release gates must run without providers."
        offline_fallback = "Run local tests, doctor, and readiness gates without network or real LLM calls."
    return {
        "deterministic_local_implementation_path": local_path,
        "optional_llm_assisted_enhancement_path": llm_path,
        "offline_fallback": offline_fallback,
        "tests_require_real_llm_api_network": False,
        "llm_dependency_policy": f"LLM is optional assistive layer only for {capability}; Core {target_version} path must remain usable without configured providers.",
    }


_CATEGORIES = [
    (
        "RAG Query Understanding",
        [
            {
                "capability": "Query Rewrite",
                "status": "missing",
                "risk_level": "P0",
                "evidence_files": ["heitang_kb_forge/retrieval/query_router.py"],
                "evidence_tests": [],
                "reason": "Current router classifies query type but does not rewrite ambiguous or underspecified user queries.",
                "user_impact": "Ambiguous user questions produce weak retrieval instead of a grounded rewritten query trace.",
                "recommended_fix": "Add rewrite contract, deterministic trace, refusal boundary, and fixture-based tests.",
                "target_version": "v3.7",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Query Expansion",
                "status": "missing",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/retrieval/query_router.py"],
                "evidence_tests": [],
                "reason": "No synonym/domain-term expansion contract is present.",
                "user_impact": "Recall can fail when the package uses different terms than the user query.",
                "recommended_fix": "Add expansion candidates with evidence-grounded constraints.",
                "target_version": "v3.7",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Query Decomposition",
                "status": "missing",
                "risk_level": "P1",
                "reason": "No decomposition of compound questions into subqueries is implemented.",
                "user_impact": "Multi-part questions can retrieve only one facet.",
                "recommended_fix": "Add decomposition plan schema and diagnostics.",
                "target_version": "v3.7",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Multi-turn Query Resolution",
                "status": "missing",
                "risk_level": "P1",
                "reason": "No conversational query state or prior-turn resolution exists in Core.",
                "user_impact": "Follow-up questions cannot be resolved against previous context.",
                "recommended_fix": "Define local session context contract before runtime memory implementation.",
                "target_version": "v3.7",
                "affects_ui": True,
            },
            {
                "capability": "Multi-query Generation",
                "status": "missing",
                "risk_level": "P0",
                "reason": "No multi-query generation or fan-out retrieval trace exists.",
                "user_impact": "Recall remains fragile for broad or underspecified tasks.",
                "recommended_fix": "Generate bounded query variants and record retrieval fan-out trace.",
                "target_version": "v3.7",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Retrieval Planning",
                "status": "missing",
                "risk_level": "P0",
                "evidence_files": ["heitang_kb_forge/planning"],
                "evidence_tests": [],
                "reason": "Planning readiness exists as a placeholder area, but no retrieval plan contract drives retriever choice.",
                "user_impact": "Users cannot see why a retrieval route was selected or refused.",
                "recommended_fix": "Add retrieval_plan.json with route, query variants, constraints, and diagnostics.",
                "target_version": "v3.7",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
        ],
    ),
    (
        "RAG Retrieval Quality",
        [
            {
                "capability": "Multi-query Recall",
                "status": "missing",
                "risk_level": "P0",
                "reason": "No multi-query retrieval fan-out or merged recall metric exists.",
                "user_impact": "Important evidence can be missed in realistic questions.",
                "recommended_fix": "Add fan-out retrieval and recall coverage report.",
                "target_version": "v3.8",
                "affects_golden_demo": True,
            },
            {
                "capability": "BM25/vector/hybrid path separation",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/retrieval", "heitang_kb_forge/vector", "heitang_kb_forge/store/query.py"],
                "evidence_tests": ["tests/test_retrieval_index.py", "tests/test_retrieval_ranking.py"],
                "reason": "Retrieval/index modules exist, but path-level separation and explainable selection are not contract-complete.",
                "user_impact": "Users cannot compare retrieval path behavior reliably.",
                "recommended_fix": "Expose path selection and per-path metrics.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Rerank",
                "status": "partial",
                "risk_level": "P0",
                "evidence_files": ["heitang_kb_forge/retrieval/ranker.py", "heitang_kb_forge/agent_rag/ranker.py", "docs/AGENT_RAG_LAYER_GUIDE.md"],
                "evidence_tests": ["tests/test_retrieval_ranking.py"],
                "reason": "Local rankers exist, but docs explicitly note no rerank service and there is no rerank contract/report.",
                "user_impact": "Top evidence ordering can be weak in dense packages.",
                "recommended_fix": "Add optional local rerank stage, trace, and disabled-by-default config.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Evidence Selection",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/knowledge_runtime/loop.py", "heitang_kb_forge/evidence_gate"],
                "evidence_tests": ["tests/test_evidence_benchmark.py"],
                "reason": "Evidence quality gates exist, but final answer evidence selection is not fully scored or explained.",
                "user_impact": "Answers may cite available evidence without explaining why it was selected.",
                "recommended_fix": "Add selected evidence report with coverage and exclusion reasons.",
                "target_version": "v3.8",
                "affects_golden_demo": True,
            },
            {
                "capability": "Evidence Coverage Scoring",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/quality/scorer.py", "heitang_kb_forge/evidence_gate"],
                "evidence_tests": ["tests/test_evidence_benchmark.py"],
                "reason": "Quality scoring exists but not a retrieval-result coverage score for user queries.",
                "user_impact": "Low-coverage answers are hard to detect before display.",
                "recommended_fix": "Add query-level coverage score and thresholded refusal path.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Retrieval Failure Diagnostics",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/retrieval/trace.py", "heitang_kb_forge/knowledge_runtime/loop.py"],
                "evidence_tests": ["tests/test_agent_rag_citation_trace.py"],
                "reason": "Trace files exist, but diagnostics do not yet classify recall, ranking, or coverage failure.",
                "user_impact": "Operators cannot quickly debug bad retrieval.",
                "recommended_fix": "Add failure taxonomy and report.",
                "target_version": "v3.8",
                "affects_ui": True,
            },
            {
                "capability": "Explainable Refusal",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/agent_package/generator.py", "heitang_kb_forge/knowledge_runtime/loop.py"],
                "evidence_tests": ["tests/test_agent_rag_ask.py"],
                "reason": "Refusal policies exist in generated agents, but retrieval-grounded refusal reports are incomplete.",
                "user_impact": "Users may not understand why a grounded answer was refused.",
                "recommended_fix": "Tie refusal to evidence coverage and boundary traces.",
                "target_version": "v3.8",
                "affects_ui": True,
            },
            {
                "capability": "Golden Query Set",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/golden_samples", "examples/golden_samples"],
                "evidence_tests": ["tests/test_golden_samples.py", "tests/test_v30_v34_core_workbench_e2e.py"],
                "reason": "Golden samples exist, but retrieval-specific golden queries are not complete.",
                "user_impact": "Retrieval regressions can pass general smoke tests.",
                "recommended_fix": "Add realistic retrieval query set with expected evidence IDs.",
                "target_version": "v3.8",
                "affects_golden_demo": True,
            },
            {
                "capability": "Retrieval Evaluation",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/eval", "heitang_kb_forge/eval_dashboard", "heitang_kb_forge/schemas/retrieval_eval_schema.py"],
                "evidence_tests": ["tests/test_retrieval_eval.py", "tests/test_retrieval_eval_export.py"],
                "reason": "Evaluation modules exist, but v3.8 needs query-set driven retrieval metrics.",
                "user_impact": "Quality cannot be compared across versions.",
                "recommended_fix": "Add repeatable retrieval eval runner and export.",
                "target_version": "v3.8",
                "affects_golden_demo": True,
            },
        ],
    ),
    (
        "Agent / Skill System",
        [
            {
                "capability": "standalone Agent",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/knowledge_bound_factory/standalone_agent.py"],
                "evidence_tests": ["tests/test_v31_knowledge_bound_factory.py", "tests/test_v31_knowledge_bound_factory_cli.py"],
                "reason": "Standalone agent generation and CLI validation are covered.",
                "user_impact": "Users can create local standalone agents.",
                "recommended_fix": "Improve smoke realism later.",
                "target_version": "v3.11",
            },
            {
                "capability": "KB-bound Agent",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/knowledge_bound_factory"],
                "evidence_tests": ["tests/test_v31_knowledge_bound_factory.py", "tests/test_v31_knowledge_bound_factory_cli.py"],
                "reason": "KB-bound generation, package/skill validation, and stable CLI business errors exist.",
                "user_impact": "Users can bind an agent to a package and skill.",
                "recommended_fix": "Add runtime realism after retrieval quality matures.",
                "target_version": "v3.11",
            },
            {
                "capability": "Skill package generation",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/skill/generator.py"],
                "evidence_tests": ["tests/test_skill_generator.py", "tests/test_v31_knowledge_bound_factory.py"],
                "reason": "Skill generation is an established Core capability.",
                "user_impact": "Users can produce skill packages from KB outputs.",
                "recommended_fix": "Keep compatibility tests current.",
                "target_version": "v3.12",
            },
            {
                "capability": "external Skill import",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/master_skill/importer.py"],
                "evidence_tests": ["tests/test_master_skill_import.py"],
                "reason": "Import exists, but external license/prompt reuse policy needs stronger audit reports.",
                "user_impact": "Unsafe external skill reuse could introduce license or prompt-copy risk.",
                "recommended_fix": "Add manual review gate and no-copy certification.",
                "target_version": "v3.12",
                "affects_golden_demo": True,
            },
            {
                "capability": "Skill reverse/fusion safety",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/skill_reverse_fusion/fusion.py"],
                "evidence_tests": ["tests/test_v33_skill_reverse_fusion.py", "tests/test_v33_skill_reverse_fusion_cli.py"],
                "reason": "Fusion exists, but external-source safety and compatibility acceptance need hardening.",
                "user_impact": "Merged skills may blur source boundaries.",
                "recommended_fix": "Add source isolation and provenance warnings.",
                "target_version": "v3.12",
            },
            {
                "capability": "Agent package validation",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/validation/package_validator.py", "heitang_kb_forge/agent_package"],
                "evidence_tests": ["tests/test_package_validation.py", "tests/test_agent_package_generator.py"],
                "reason": "Validation exists, but generated package compatibility is not yet product-grade.",
                "user_impact": "Invalid packages can survive until late smoke tests.",
                "recommended_fix": "Add stricter compatibility matrix and realistic fixtures.",
                "target_version": "v3.12",
            },
            {
                "capability": "generated package compatibility",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/agent_compat"],
                "evidence_tests": ["tests/test_agent_compat_checker.py", "tests/test_agent_compat_codex.py"],
                "reason": "Compatibility exporters/checkers exist, but not all generated artifacts are verified end-to-end.",
                "user_impact": "Generated packages may be hard to open in target tools.",
                "recommended_fix": "Add real acceptance smoke in v3.11 and hardening in v3.12.",
                "target_version": "v3.11",
                "affects_golden_demo": True,
            },
            {
                "capability": "smoke test realism",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/knowledge_bound_factory/standalone_agent.py"],
                "evidence_tests": ["tests/test_v31_knowledge_bound_factory.py", "tests/test_v30_v34_core_workbench_e2e.py"],
                "reason": "Smoke tests are deterministic but still synthetic.",
                "user_impact": "Golden Demo may not reveal real package issues.",
                "recommended_fix": "Add real input acceptance smoke.",
                "target_version": "v3.11",
                "affects_golden_demo": True,
            },
        ],
    ),
    (
        "External Retrieval for Knowledge Accuracy Verification",
        [
            {
                "capability": "claim extraction from a KB package",
                "status": "partial",
                "risk_level": "P0",
                "evidence_files": ["heitang_kb_forge/skill/rules.py", "docs/AGENT_KB_ANSWER_POLICY.md"],
                "evidence_tests": [],
                "reason": "Core requires evidence-aware factual claims, but does not extract package claims into a verification queue.",
                "user_impact": "Knowledge accuracy cannot be audited at claim level.",
                "recommended_fix": "Add claim_check input records generated from package chunks with source IDs and confidence.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "claim-level evidence mapping",
                "status": "partial",
                "risk_level": "P0",
                "evidence_files": ["heitang_kb_forge/evidence_gate", "heitang_kb_forge/quality/scorer.py"],
                "evidence_tests": ["tests/test_evidence_benchmark.py"],
                "reason": "Evidence gates exist, but claims are not mapped one-by-one to internal and external evidence.",
                "user_impact": "Users cannot see why an individual KB claim is trusted or weak.",
                "recommended_fix": "Add claim_verification_report with claim_id, internal_evidence, external_evidence, and status.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "external source retrieval for verification",
                "status": "missing",
                "risk_level": "P0",
                "reason": "No external verification retrieval contract exists, and v3.6 intentionally does not implement real web search.",
                "user_impact": "KB freshness and accuracy cannot be checked against external sources.",
                "recommended_fix": "In v3.7 define verification-oriented retrieval planning separate from answer retrieval; implement opt-in local report flow in v3.8.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "source cross-checking",
                "status": "missing",
                "risk_level": "P0",
                "reason": "Core does not compare a KB claim against multiple independent sources.",
                "user_impact": "Single-source or stale claims can appear reliable.",
                "recommended_fix": "Add source_cross_check report with agreement, disagreement, and insufficient-evidence states.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "contradiction detection",
                "status": "missing",
                "risk_level": "P0",
                "reason": "No contradiction detector or contradiction report exists for KB claims.",
                "user_impact": "Contradicted knowledge can remain in generated packages and agents.",
                "recommended_fix": "Add contradiction_detection records based on claim/source disagreement.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "freshness verification",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/refresh/checker.py"],
                "evidence_tests": ["tests/test_refresh_check.py"],
                "reason": "Source freshness reporting exists, but it does not verify claim freshness against external sources.",
                "user_impact": "Users may trust claims whose source documents are locally fresh but externally outdated.",
                "recommended_fix": "Add freshness_check tied to external verification retrieval and package lifecycle status.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "outdated knowledge detection",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/refresh/checker.py", "docs/KNOWLEDGE_OPS_GUIDE.md"],
                "evidence_tests": ["tests/test_refresh_check.py"],
                "reason": "Stale source detection exists, but outdated claims are not detected through cross-source verification.",
                "user_impact": "Old claims can survive package refresh checks.",
                "recommended_fix": "Extend v4.3 governance with scheduled freshness review and outdated package warnings.",
                "target_version": "v4.3",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "source disagreement report",
                "status": "missing",
                "risk_level": "P1",
                "reason": "No report records disagreement history between KB claims and external sources.",
                "user_impact": "Reviewers cannot decide whether a claim should be demoted or updated.",
                "recommended_fix": "Add source disagreement report in v3.8 and history retention in v4.3.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "knowledge accuracy scoring",
                "status": "partial",
                "risk_level": "P0",
                "evidence_files": ["heitang_kb_forge/quality/scorer.py"],
                "evidence_tests": ["tests/test_evidence_benchmark.py"],
                "reason": "Quality scoring includes accuracy-like fields for local evidence, but no claim verification accuracy score exists.",
                "user_impact": "Users cannot compare KB trustworthiness across packages.",
                "recommended_fix": "Add knowledge_accuracy_score derived from claim verification outcomes.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "verification retrieval trace",
                "status": "missing",
                "risk_level": "P0",
                "reason": "Answer retrieval traces exist, but validation retrieval needs its own purpose, source policy, and trace.",
                "user_impact": "External verification cannot be audited or separated from answer generation.",
                "recommended_fix": "Add verification_retrieval_trace that distinguishes answer retrieval from validation retrieval.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "claim verification report",
                "status": "missing",
                "risk_level": "P0",
                "reason": "No claim verification report exists.",
                "user_impact": "Users cannot inspect trusted, weak, outdated, or contradicted claims.",
                "recommended_fix": "Add claim_verification_report with per-claim status and user-facing explanation.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "user-facing explanation of claim trust status",
                "status": "missing",
                "risk_level": "P0",
                "reason": "Core does not generate explanations for trusted, weak, outdated, or contradicted KB claims.",
                "user_impact": "Users cannot understand why a claim should or should not be trusted.",
                "recommended_fix": "Expose explanation fields in claim_verification_report and Workbench contracts.",
                "target_version": "v3.8",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
        ],
    ),
    (
        "Local Document Parsing & PDF Token Reduction",
        [
            {
                "capability": "local PDF to Markdown preprocessing",
                "status": "missing",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/parsers/pdf_parser.py", "heitang_kb_forge/parsers/markdown_parser.py"],
                "evidence_tests": ["tests/test_pdf_parser.py", "tests/test_all_formats_build.py"],
                "reason": "Core parses PDF text locally and accepts Markdown, but does not emit a LiteDoc-like PDF-to-Markdown preprocessing artifact before KB ingestion.",
                "user_impact": "Users cannot inspect or reuse a local Markdown intermediate before chunking.",
                "recommended_fix": "Add local PDF-to-Markdown preprocessing report and artifact in the parser hardening track without integrating LiteDoc directly.",
                "target_version": "v3.9",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "parser backend selection",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/parser_backends/registry.py", "heitang_kb_forge/parser_backends/docling_adapter.py", "heitang_kb_forge/parser_backends/marker_adapter.py", "heitang_kb_forge/schemas/config_schema.py"],
                "evidence_tests": ["tests/test_v28_parser_backends.py"],
                "reason": "Builtin, Docling, and Marker parser backend strategy exists and remains optional.",
                "user_impact": "Operators can route parsing through local optional backends.",
                "recommended_fix": "Add backend benchmark and comparison report before expanding parser choices.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "scanned PDF detection",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/parsers/pdf_preflight.py", "heitang_kb_forge/parsers/pdf_parser.py"],
                "evidence_tests": ["tests/test_ocr_page_selection.py", "tests/test_batch_build.py"],
                "reason": "PDF preflight and OCR fallback detect pages needing OCR.",
                "user_impact": "Scanned PDFs can be routed to local OCR when configured.",
                "recommended_fix": "Expose scanned-PDF detection in parser benchmark reporting.",
                "target_version": "v3.9",
            },
            {
                "capability": "OCR backend routing",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/parsers/pdf_parser.py", "heitang_kb_forge/ocr/worker.py"],
                "evidence_tests": ["tests/test_ocr_cache.py", "tests/test_ocr_resume_report.py"],
                "reason": "Local OCR fallback exists, but PaddleOCR-like backend choice is not modeled as a pluggable OCR backend contract.",
                "user_impact": "Scanned document quality depends on the current optional OCR path.",
                "recommended_fix": "Add OCR backend registry and benchmark report while keeping PaddleOCR optional.",
                "target_version": "v3.9",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "complex layout parser routing",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/parser_backends/docling_adapter.py", "heitang_kb_forge/parser_backends/marker_adapter.py", "heitang_kb_forge/multimodal"],
                "evidence_tests": ["tests/test_v28_parser_backends.py", "tests/test_multimodal_assets.py"],
                "reason": "Optional complex parser adapters exist, but MinerU-like layout/table/formula routing is not benchmarked or selected by document complexity.",
                "user_impact": "Complex PDFs can produce weaker Markdown/JSON intermediates.",
                "recommended_fix": "Add complexity-based parser routing and backend comparison reports.",
                "target_version": "v3.9",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "table/formula/layout fallback",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/parsers/pdf_table_parser.py", "heitang_kb_forge/multimodal/formula_assets.py"],
                "evidence_tests": ["tests/test_pdf_table_parser.py", "tests/test_multimodal_assets.py"],
                "reason": "Table and formula handling exists in local components, but fallback policy is not centralized across parser backends.",
                "user_impact": "Complex layout evidence can be inconsistent across formats.",
                "recommended_fix": "Add parser fallback policy and per-backend capability report.",
                "target_version": "v3.9",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "image extraction policy",
                "status": "partial",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/multimodal/image_assets.py", "heitang_kb_forge/parsers/image_parser.py"],
                "evidence_tests": ["tests/test_multimodal_image_assets.py", "tests/test_image_parser.py"],
                "reason": "Image extraction and multimodal assets exist, but parser-backend image policy is not benchmarked against complex document parsers.",
                "user_impact": "Image-derived evidence may require extra review in complex documents.",
                "recommended_fix": "Add image policy rows to parser backend benchmark report.",
                "target_version": "v3.9",
            },
            {
                "capability": "corrupted font handling",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/parser_backends/quality.py", "heitang_kb_forge/parsers/pdf_preflight.py"],
                "evidence_tests": ["tests/test_v28_parser_backends.py"],
                "reason": "Low-confidence parse handling exists, but corrupted font detection and fallback are not explicit.",
                "user_impact": "PDF text layers with bad fonts can silently degrade extracted knowledge.",
                "recommended_fix": "Add corrupted-font warning taxonomy and fallback path.",
                "target_version": "v3.9",
                "affects_golden_demo": True,
            },
            {
                "capability": "parser confidence report",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/parser_backends/quality.py"],
                "evidence_tests": ["tests/test_v28_parser_backends.py"],
                "reason": "Parser confidence and manual review queue are represented in parse quality reports.",
                "user_impact": "Low-confidence parse output can be marked for review.",
                "recommended_fix": "Tie confidence into parser benchmark and token reduction reporting.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "token cost reduction report",
                "status": "missing",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/llm/quality.py", "heitang_kb_forge/cli_runtime.py"],
                "evidence_tests": [],
                "reason": "LLM token/cost guard exists, but parser output does not report raw-PDF avoided token waste or Markdown intermediate savings.",
                "user_impact": "Users cannot quantify why local parsing before LLM use protects budget.",
                "recommended_fix": "Add pdf_token_reduction report that compares raw document size, parsed Markdown size, and chunked retrieval payload.",
                "target_version": "v3.9",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "no-cloud-upload guarantee",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["docs/RELEASE_CHECKLIST.md", "docs/PROJECT_ARCHITECTURE_OVERVIEW.md", "heitang_kb_forge/platform_distribution"],
                "evidence_tests": ["tests/test_release_checklist_docs.py", "tests/test_platform_upload_check.py"],
                "reason": "Core repeatedly documents and tests local/offline boundaries and no upload behavior.",
                "user_impact": "Users can rely on local-first document handling by default.",
                "recommended_fix": "Add parser-specific no-upload invariant to v3.9 reports.",
                "target_version": "v3.9",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "parser backend benchmark report",
                "status": "missing",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/parser_backends"],
                "evidence_tests": [],
                "reason": "Parser adapters and quality reports exist, but there is no benchmark comparing builtin, Docling, Marker, PaddleOCR-like OCR, or MinerU-like complex parsing.",
                "user_impact": "Operators cannot choose a parser backend based on measured quality/cost/privacy tradeoffs.",
                "recommended_fix": "Add parser_backend_benchmark_report with local-only fixtures and no network dependency.",
                "target_version": "v3.9",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
        ],
    ),
    (
        "Agent Memory / Runtime",
        [
            {
                "capability": "session memory",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/multi_kb_orchestration/orchestrator.py"],
                "evidence_tests": ["tests/test_v32_multi_kb_orchestration.py"],
                "reason": "Session log fields exist as contracts, but no real runtime session store exists.",
                "user_impact": "Users cannot resume a real agent session.",
                "recommended_fix": "Add local memory lifecycle storage.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "short-term memory",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/multi_kb_orchestration/orchestrator.py"],
                "evidence_tests": ["tests/test_v32_multi_kb_orchestration.py"],
                "reason": "Contract field exists without operational persistence.",
                "user_impact": "Recent task context is not robust across operations.",
                "recommended_fix": "Implement local bounded short-term memory store.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "summary memory",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Summary memory appears in lifecycle reports but is not compacted from sessions.",
                "user_impact": "Long sessions cannot be summarized reliably.",
                "recommended_fix": "Add deterministic summary-memory placeholder and compaction report.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "long-term memory",
                "status": "missing",
                "risk_level": "P1",
                "reason": "User explicitly deferred a real long-term memory database; Core only has contracts.",
                "user_impact": "Durable memory is unavailable.",
                "recommended_fix": "Add local-first long-term memory lifecycle after storage abstraction.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "memory candidates",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/multi_kb_orchestration/orchestrator.py"],
                "evidence_tests": ["tests/test_v32_multi_kb_orchestration.py"],
                "reason": "Candidate queue and writeback report are generated by v3.2 contracts.",
                "user_impact": "Selective writeback can be represented safely.",
                "recommended_fix": "Connect to local memory lifecycle in v3.9.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "memory index",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Memory index field exists in contracts but no indexer is implemented.",
                "user_impact": "Memory lookup remains contract-only.",
                "recommended_fix": "Add local memory index metadata and size reporting.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "memory compaction",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Compaction policy/status exists, but compaction is not performed.",
                "user_impact": "Large memory artifacts cannot be reduced.",
                "recommended_fix": "Add compaction planner and report.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "memory promotion",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/multi_kb_orchestration/orchestrator.py"],
                "evidence_tests": ["tests/test_v32_multi_kb_orchestration.py"],
                "reason": "Promotion report exists as a review contract.",
                "user_impact": "Workbench can show pending memory promotion status.",
                "recommended_fix": "Add promotion action runtime later.",
                "target_version": "v3.10",
                "affects_ui": True,
            },
            {
                "capability": "mother/child Agent memory isolation",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/multi_kb_orchestration/orchestrator.py"],
                "evidence_tests": ["tests/test_v32_multi_kb_orchestration.py"],
                "reason": "v3.2 reports enforce child private memory by default.",
                "user_impact": "Child agents can be represented without accidental shared memory.",
                "recommended_fix": "Validate with real runtime in v3.10.",
                "target_version": "v3.10",
                "affects_ui": True,
            },
            {
                "capability": "workflow shared memory",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/multi_kb_orchestration/orchestrator.py"],
                "evidence_tests": ["tests/test_v32_multi_kb_orchestration.py"],
                "reason": "Explicit workflow_shared_memory flag is represented.",
                "user_impact": "Shared memory can be displayed only when explicitly enabled.",
                "recommended_fix": "Add runtime enforcement in v3.10.",
                "target_version": "v3.10",
                "affects_ui": True,
            },
            {
                "capability": "selective parent writeback",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/multi_kb_orchestration/orchestrator.py"],
                "evidence_tests": ["tests/test_v32_multi_kb_orchestration.py"],
                "reason": "Parent writeback creates queued candidates rather than direct parent writes.",
                "user_impact": "Parent memory is protected from implicit child writes.",
                "recommended_fix": "Add approval runtime later.",
                "target_version": "v3.10",
                "affects_ui": True,
            },
            {
                "capability": "token budget policy",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Token budget policy is exposed in lifecycle fields but not enforced by runtime.",
                "user_impact": "Long workflows may exceed practical context budgets.",
                "recommended_fix": "Add budget accounting and compression status.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
        ],
    ),
    (
        "Storage / Workspace",
        [
            {
                "capability": "local workspace registry",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/workspace/registry.py"],
                "evidence_tests": ["tests/test_workspace_registry.py"],
                "reason": "Workspace registry exists for local outputs.",
                "user_impact": "Local assets can be registered.",
                "recommended_fix": "Add usage and cleanup status in v3.9.",
                "target_version": "v3.9",
            },
            {
                "capability": "package registry",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/store"],
                "evidence_tests": ["tests/test_store_import_package.py", "tests/test_store_query_packages.py"],
                "reason": "Package store exists but storage abstraction is not contract-complete.",
                "user_impact": "Workbench storage status is incomplete.",
                "recommended_fix": "Normalize package storage report and size metrics.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "skill registry",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/workspace_refresh"],
                "evidence_tests": ["tests/test_v34_workbench_contracts.py"],
                "reason": "Skill assets are discoverable but no dedicated registry lifecycle exists.",
                "user_impact": "Workbench cannot fully manage skill storage.",
                "recommended_fix": "Add skill registry contract and cleanup hints.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "agent registry",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "evidence_tests": ["tests/test_v34_workbench_contracts.py"],
                "reason": "Agent assets are contracted but registry lifecycle is limited.",
                "user_impact": "Workbench cannot fully track local agent package size/status.",
                "recommended_fix": "Add agent registry report.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "memory registry",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Memory storage status exists but no registry of memory artifacts exists.",
                "user_impact": "Users cannot inspect memory growth or cleanup consistently.",
                "recommended_fix": "Add memory registry and lifecycle size report.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "index registry",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/retrieval/index_builder.py"],
                "evidence_tests": ["tests/test_retrieval_index.py"],
                "reason": "Indexes are built but not managed through a storage registry.",
                "user_impact": "Index size and freshness are hard to inspect.",
                "recommended_fix": "Add index registry and size report.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "storage usage report",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "evidence_tests": ["tests/test_v34_workbench_contracts.py"],
                "reason": "Workbench storage contract reports sizes, but no general Core storage report exists.",
                "user_impact": "Users lack cleanup guidance outside workbench contracts.",
                "recommended_fix": "Add storage_usage_report.json.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "dedup",
                "status": "missing",
                "risk_level": "P2",
                "reason": "No storage-level dedup policy exists.",
                "user_impact": "Repeated outputs may grow workspace size.",
                "recommended_fix": "Add hash-based dedup plan after registry work.",
                "target_version": "v3.12",
            },
            {
                "capability": "cleanup policy",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "reason": "Cleanup suggestions exist in Workbench storage contract but are not generalized.",
                "user_impact": "Users cannot automate local cleanup safely.",
                "recommended_fix": "Add non-destructive cleanup suggestions and reports.",
                "target_version": "v3.9",
                "affects_ui": True,
            },
            {
                "capability": "local_db placeholder",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "evidence_tests": ["tests/test_v34_workbench_contracts.py"],
                "reason": "local_db is reserved as future backend.",
                "user_impact": "Future storage can be planned without cloud requirements.",
                "recommended_fix": "Keep placeholder inactive until v3.9.",
                "target_version": "v3.9",
            },
            {
                "capability": "BYO cloud placeholder",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "reason": "byo_cloud is reserved while platform-hosted data remains false.",
                "user_impact": "Future cloud compatibility does not imply SaaS data hosting.",
                "recommended_fix": "Keep BYO-only contract explicit.",
                "target_version": "v4.0",
                "affects_ui": True,
            },
            {
                "capability": "no platform-hosted data",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "reason": "Storage contracts keep default backend local_workspace and BYO cloud non-platform-hosted.",
                "user_impact": "Users retain local-first data expectations.",
                "recommended_fix": "Preserve as release invariant.",
                "target_version": "v4.0",
                "affects_ui": True,
            },
        ],
    ),
    (
        "Workbench / UI Contracts",
        [
            {
                "capability": "navigation contract completeness",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "evidence_tests": ["tests/test_v34_workbench_contracts.py"],
                "reason": "Navigation covers v3.4 assets, but future query/retrieval/memory views are not complete.",
                "user_impact": "UI can drift as Core adds v3.7-v3.10 contracts.",
                "recommended_fix": "Add contract drift tests per future version.",
                "target_version": "v4.0",
                "affects_ui": True,
            },
            {
                "capability": "action contract completeness",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py"],
                "evidence_tests": ["tests/test_v34_workbench_contracts_cli.py"],
                "reason": "Actions exist for current workflows, but future query/rerank/memory operations are absent.",
                "user_impact": "Workbench cannot expose future Core operations safely.",
                "recommended_fix": "Version action contract with each new Core operation.",
                "target_version": "v4.0",
                "affects_ui": True,
            },
            {
                "capability": "asset contract completeness",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Current assets are scanned from known files; future reports need explicit registration.",
                "user_impact": "Generated artifacts may be invisible in Workbench.",
                "recommended_fix": "Add asset schema coverage for v3.7-v3.12 reports.",
                "target_version": "v4.0",
                "affects_ui": True,
            },
            {
                "capability": "status contract completeness",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Status includes memory/storage basics but not retrieval quality or release readiness status.",
                "user_impact": "UI cannot show full product readiness.",
                "recommended_fix": "Add quality, eval, and release status fields.",
                "target_version": "v4.0",
                "affects_ui": True,
            },
            {
                "capability": "error contract completeness",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Generic error states exist, but query/retrieval/runtime-specific errors are missing.",
                "user_impact": "UI may render unstable ad hoc errors.",
                "recommended_fix": "Add stable error taxonomy for future features.",
                "target_version": "v4.0",
                "affects_ui": True,
            },
            {
                "capability": "contract-driven UI readiness",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/workbench_contracts/contracts.py", "tests/test_v34_workbench_contracts.py"],
                "reason": "Contracts exist, but v4.0 readiness needs broader contract coverage and drift tests.",
                "user_impact": "UI integration could regress if Core contracts change silently.",
                "recommended_fix": "Add contract fixtures and compatibility matrix.",
                "target_version": "v4.0",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "Core/UI contract drift risk",
                "status": "partial",
                "risk_level": "P0",
                "reason": "UI is intentionally frozen while Core evolves through v3.6+.",
                "user_impact": "Later UI work can mismatch Core output unless drift is audited.",
                "recommended_fix": "Generate v4.0 contract drift audit before UI integration resumes.",
                "target_version": "v4.0",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
        ],
    ),
    (
        "Product Readiness",
        [
            {
                "capability": "Golden Demo readiness",
                "status": "partial",
                "risk_level": "P0",
                "evidence_files": ["tests/test_v30_v34_core_workbench_e2e.py", "heitang_kb_forge/golden_samples"],
                "evidence_tests": ["tests/test_v30_v34_core_workbench_e2e.py"],
                "reason": "Core E2E exists, but realistic query/retrieval/runtime acceptance is incomplete.",
                "user_impact": "Demo can pass while missing product-critical retrieval behavior.",
                "recommended_fix": "Add real acceptance smoke after v3.7-v3.10.",
                "target_version": "v3.11",
                "affects_ui": True,
                "affects_golden_demo": True,
            },
            {
                "capability": "real input sample coverage",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["examples/golden_samples", "heitang_kb_forge/golden_samples"],
                "reason": "Golden samples exist, but coverage is not yet representative enough.",
                "user_impact": "Release confidence remains limited.",
                "recommended_fix": "Add representative local samples and acceptance checks.",
                "target_version": "v3.11",
                "affects_golden_demo": True,
            },
            {
                "capability": "generated artifact openability",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/document_generation", "heitang_kb_forge/export_certification"],
                "evidence_tests": ["tests/test_v30_document_generation.py", "tests/test_export_certification.py"],
                "reason": "Document and export reports exist, but end-user openability smoke needs strengthening.",
                "user_impact": "Generated files might be valid enough for tests but not useful enough for demo.",
                "recommended_fix": "Add real openability smoke for generated artifacts.",
                "target_version": "v3.11",
                "affects_golden_demo": True,
            },
            {
                "capability": "CLI error stability",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/cli_runtime.py"],
                "evidence_tests": ["tests/test_v31_knowledge_bound_factory_cli.py"],
                "reason": "Recent CLI hardening exists, but future commands need stable business-error tests.",
                "user_impact": "CI and users can see inconsistent Typer/Rich validation output.",
                "recommended_fix": "Add business error tests for each new CLI option group.",
                "target_version": "v3.12",
                "affects_golden_demo": True,
            },
            {
                "capability": "CI parity",
                "status": "partial",
                "risk_level": "P1",
                "reason": "Full pytest passes locally in prior versions, but CI parity still needs continuous watch.",
                "user_impact": "Local green can fail remotely if environment differs.",
                "recommended_fix": "Keep no-network tests and stable CLI output.",
                "target_version": "v3.12",
                "affects_golden_demo": True,
            },
            {
                "capability": "doctor/diagnostics",
                "status": "exists",
                "risk_level": "P2",
                "evidence_files": ["heitang_kb_forge/doctor.py", "heitang_kb_forge/cli_commands/doctor_commands.py"],
                "evidence_tests": ["tests/test_doctor_command.py", "tests/test_doctor_cli.py"],
                "reason": "Doctor command and tests exist.",
                "user_impact": "Users can inspect baseline environment health.",
                "recommended_fix": "Add v3.7-v3.12 diagnostics as features land.",
                "target_version": "v3.12",
            },
            {
                "capability": "troubleshooting",
                "status": "partial",
                "risk_level": "P2",
                "evidence_files": ["docs/TROUBLESHOOTING.md"],
                "reason": "Troubleshooting docs exist, but new v3.x workflows need updates.",
                "user_impact": "Users may lack recovery paths for new workflows.",
                "recommended_fix": "Update troubleshooting after product hardening.",
                "target_version": "v3.12",
            },
            {
                "capability": "release readiness",
                "status": "partial",
                "risk_level": "P1",
                "evidence_files": ["heitang_kb_forge/release_readiness", "heitang_kb_forge/release_blockers"],
                "evidence_tests": ["tests/test_release_readiness.py", "tests/test_release_readiness_gate.py"],
                "reason": "Release readiness modules exist, but v3.7-v4.0 must pass new acceptance gates.",
                "user_impact": "A release could ship with missing query/retrieval/runtime capabilities.",
                "recommended_fix": "Add release blocker checks for P0 gaps.",
                "target_version": "v3.12",
                "affects_golden_demo": True,
            },
        ],
    ),
]


def gap_items() -> list[dict]:
    return deepcopy(architecture_gap_audit_report()["gap_items"])
