from pathlib import Path


def evidence_score(skill: Path, package: Path) -> tuple[int, list[str]]:
    warnings = []
    if not (package / "chunks.jsonl").exists():
        warnings.append("missing_chunks")
    if "Generated by:" not in (skill / "knowledge_scope.md").read_text(encoding="utf-8"):
        warnings.append("missing_generation_marker")
    return (100 if not warnings else 60), warnings
