from pathlib import Path


def style_score(skill: Path) -> tuple[int, list[str]]:
    path = skill / "style_rules.md"
    if not path.exists():
        return 0, ["missing_style_rules"]
    text = path.read_text(encoding="utf-8")
    if "Generated by:" not in text:
        return 70, ["style_rules_missing_generation_marker"]
    return 100, []
