REGRESSION_BASELINE = [
    ("v1.6", "contract_multimodal_ocr_complex_ingestion", "tests/test_package_contract_v2.py"),
    ("v1.7", "governance_retrieval_evidence_gate", "tests/test_evidence_gate.py"),
    ("v1.8", "skill_agent_package_validation", "tests/test_v18_cli_commands.py"),
    ("v1.9", "workspace_registry_prompt_profile_llm_audit", "tests/test_v19_config.py"),
    ("v2.0", "stable_provider_reliability_release", "tests/test_v20_config.py"),
    ("v2.1", "input_hardening_quality_review_eval", "tests/test_v21_config.py"),
    ("v2.2", "master_skill_derived_skill_agent_compat", "tests/test_v22_config.py"),
    ("v2.3", "batch_lineage_curation_update_impact", "tests/test_v23_config.py"),
    ("v2.4", "platform_distribution_upload_mock_publish", "tests/test_v24_config.py"),
    ("v2.5.0-dev", "release_quality_gate_regression_certification", "tests/test_v25_config.py"),
    ("v2.5.1-alpha.1", "release_engineering_cli_architecture_convergence", "tests/test_version_alignment.py"),
    ("v2.6.0-alpha.1", "provider_security_governance_and_live_smoke", "tests/test_v26_provider_security.py"),
    ("v2.7.0-alpha.1", "minimal_demo_e2e_portfolio_release", "tests/test_v27_demo_e2e.py"),
]
